-- Mic Quest: Polar Pattern Run
-- Run this in the Supabase SQL editor before beta testing.

create table if not exists public.mic_quest_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 40),
  score integer not null check (score between 0 and 60),
  total integer not null default 60 check (total between 1 and 60),
  perfect integer not null default 0 check (perfect between 0 and 15),
  time_ms integer not null check (time_ms between 0 and 3600000),
  mode text not null default '' check (char_length(mode) <= 30),
  created_at timestamptz not null default now()
);

alter table public.mic_quest_scores enable row level security;

drop policy if exists "Anyone can read mic quest scores" on public.mic_quest_scores;
drop policy if exists "Anyone can submit mic quest scores" on public.mic_quest_scores;

create policy "Anyone can read mic quest scores"
on public.mic_quest_scores
for select
to anon
using (true);

create policy "Anyone can submit mic quest scores"
on public.mic_quest_scores
for insert
to anon
with check (
  char_length(player_name) between 1 and 40
  and score between 0 and 60
  and total between 1 and 60
  and perfect between 0 and 15
  and time_ms between 0 and 3600000
  and char_length(mode) <= 30
);

grant usage on schema public to anon;
grant select, insert on public.mic_quest_scores to anon;
